### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by ujjaldas1997** [chinakook/hr101_mxnet#1]
Can you give the details of gpu, and running time? I had run both mxnet and matconvnet version and both were taking huge amount of time(about 250 sec for selfie.jpg).
Also will you release the training code of the same?

**Comment by chinakook** [comment]
@ujjaldas1997 Both implementations are less than 3 sec on my GTX 1070(with CUDNN 5.1). No training code in mxnet until now.

**Comment by ujjaldas1997** [comment]
Ahh, in my case it is --
`01:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940M] (rev a2)`
I think performance issue is because of this. Are you working on training mxnet for hr_res_101?
Thank you.

**Comment by chinakook** [comment]
@ujjaldas1997  I think that training is trivial because the tiny face is virtually a RPN of Faster RCNN(just with a FCN skip connection added). I have no plan to write training scripts in mxnet recently, but I think you can refer to a RPN of FRCNN training.

**Comment by ujjaldas1997** [comment]
Yes and thanks. I have almost finished training code(using keras library the traditional way), and thinking of switching to mxnet as it is faster. 
And thanks again for the direction.
