### ISSUE TITLE
Cannot reproduce the results as in the paper

### ISSUE THREAD

**Issue by fengyuentau** [chinakook/hr101_mxnet#13]
Due to software restriction, I cannot run the official matlab code.

So I try to get the same results as shown in the paper using this repo, but failed. I also tried with OpenCV 2.4, but it did not help.

Here is what I got on validation set:

| | AP_easy | AP_medium | AP_hard |
| - | - | - | - |
| hr-resnet101-mxnet (this repo) | 0.926 | 0.904 | 0.768 |
| hr-resnet101-mxnet (this repo) + OpenCV 2.4 | 0.923 | 0.901 | 0.769 |
| hr-resnet101-matlab ([official](https://github.com/peiyunh/tiny)) | 0.923 | 0.910 | 0.819 |

I do not think the version of OpenCV has great impact on the AP, since you only use it for reading and resizing images. Can you reproduce the results as the paper claims?

**Comment by chinakook** [comment]
Matlab's imresize use antialias, This is the only different. this repo is obsolete, you can use https://github.com/deepinsight/insightface/tree/master/RetinaFace , which would be better.
