### ISSUE TITLE
Partial detection issues, do you know why?

### ISSUE THREAD

**Issue by Tetsujinfr** [chinakook/hr101_mxnet#5]
On an image, where there are lots of faces, I have only the low part of the image where faces are recognized very well, but the upper part is almost empty.
- Is there a max number of faces that can be detected ? (I could not identify any such limit in the code)
- can sharp images be an issue?

Thanks

**Comment by chinakook** [comment]
No maximum limit, you can upload your image and let me see.

**Comment by Tetsujinfr** [comment]
sure, here it is:

![selfie_charlie_out](https://user-images.githubusercontent.com/29961693/30452535-e7e8f196-998d-11e7-8fdb-aa3d9f01bea7.jpg)

**Comment by chinakook** [comment]
@Tetsujinfr your image size is 5000x3333, so the detector will not upsample the image up to 2x and 4x to detect small faces. If you want to detect small faces in such a big image, you need to  split the origin image to 4 parts or 9 parts then do detection one by one.

**Comment by Tetsujinfr** [comment]
But why did it work partially then? Is the image cropped by the code if bigger than a given resolution?

**Comment by chinakook** [comment]
No, the faces in the upper part is too dense and small so can not be detected in a 1x scale, but the lower part can be detected in the same scale.
You can crop a roi from the upper part to test the detector.

**Comment by Tetsujinfr** [comment]
Ok thanks, I will give it a try. I need to re-read the paper because I was under the impression that the strength of Tiny face was actually to detect faces with very small pixels coverage.
Can I tweak the Max_dimension static vatiable or that would require re-training the model (which I want to avoid)

**Comment by chinakook** [comment]
No need to re-training

**Comment by Tetsujinfr** [comment]
ok, could not increase the max_dim variable since it triggers a memory alloc issue on my 6gb 980Ti (I tried 8000 then 6000) but by cropping the image in two pieces did work indeed.
thanks for your advice to split:


![selfie_charlie_detect_2parts_m](https://user-images.githubusercontent.com/29961693/30507048-cc53cb4a-9a78-11e7-8e7d-3303e44b20bc.jpg)

Tets
